### ISSUE TITLE
Duplicate identifier when compiling with HAVE_EPOLL=0 and HAVE_KQUEUE=0

### ISSUE THREAD

**Issue by futile** [NTAP/warpcore#13]
When compiling without epoll and kqueue (so with poll), the following identifier appears twice, see:

https://github.com/NTAP/warpcore/blob/e180c400043a3053506cdf760f3e625e6b7ba4cc/lib/src/backend.h#L62

and

https://github.com/NTAP/warpcore/blob/e180c400043a3053506cdf760f3e625e6b7ba4cc/lib/src/backend.h#L66

This is obviously wrong (doesn't compile), but I'm not sure what the semantics here should be (two padding fields? only one?).

**Comment by larseggert** [comment]
Thanks for the report. This should hopefully be fixed now. I need to get better at having CI test all the config combinations.
