### ISSUE TITLE
Error: unknown type name 'fd_set'

### ISSUE THREAD

**Issue by lvjiamei** [NTAP/warpcore#17]
Hi! I want to run a QUIC example based on warpcore.  I encountered an error when making the project.  The log is:
`/riotproject/lib/deps/warpcore/lib/src/backend.h:88:5: error: unknown type name 'fd_set'
   88 |     fd_set fds;` 
I searched the warpcore and couldn't find the definition of ‘fd_set’. Is it a bug? or how could I fix the error? Thanks!

**Comment by larseggert** [comment]
What RIOT platform are you trying? I only tested with ESP32. The missing definition should be per of the board toolchain.

**Comment by lvjiamei** [comment]
> What RIOT platform are you trying? I only tested with ESP32. The missing definition should be per of the board toolchain.

I tested with Nrf52840. I solved the problem. The missing definition is in RIOT/select.h . Thanks a lot for your apply!!!

**Comment by larseggert** [comment]
Please submit a PR is this is a fix that is of general interest! Glad to hear you got it working.
